# Generated by Django 5.2.1 on 2025-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_consultation_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
